version: "3"
services:
  app:
    build: .
    ports:
      - "3333:3333"
    depends_on:
      - mongoDB
  mongoDB:
    image: mongo
    volumes:
      - ./data:/data/db
    ports:
      - "27017:27017"
